services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ledgerflow
      POSTGRES_USER: ledgerflow
      POSTGRES_PASSWORD: ledgerflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledgerflow"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:3.8.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,HOST://:29092,CONTROLLER://:9093
      # PLAINTEXT is for clients inside the docker network (the 'app' service);
      # HOST is for the Spring Boot app run directly on the Windows host.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  fraud-service:
    build: ./fraud-service
    ports:
      - "8000:8000"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
      fraud-service:
        condition: service_started
    environment:
      DB_URL: jdbc:postgresql://db:5432/ledgerflow
      DB_USER: ledgerflow
      DB_PASSWORD: ledgerflow
      KAFKA_BOOTSTRAP: kafka:9092
      EVENTS_TRANSPORT: kafka
      FRAUD_BASE_URL: http://fraud-service:8000
    ports:
      - "8080:8080"
